config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  root 'pages#home'

  match '/', to: 'pages#home', via: 'get'
  match '/game', to: 'pages#game', via: 'get'
  match '/add_player', to: 'pages#add_player', via: 'post'
  match '/about', to: 'pages#about', via: 'get'
  match '/contact', to: 'pages#contact', via: 'get'
  match '/profile', to: 'pages#profile', via: 'get'
  match '/deposit', to: 'pages#deposit', via: 'get'
  match '/withdraw', to: 'pages#withdraw', via: 'get'
  match '/schedule', to: 'pages#schedule', via: 'get'
  match '/about_game', to: 'pages#about_game', via: 'get'

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.has_role?('admin')
      can :access, :rails_admin       # only allow admin users to access Rails Admin
      can :dashboard           
      can :manage, :all
    else
      can :read, :all
    end
  end
end

app/models/game.rb
class Game < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/role.rb
class Role < ActiveRecord::Base
	has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
 
  has_many :user_transactions
  has_and_belongs_to_many :games
  
  validates :login, :phone, :email, :password, :presence => {message: "Не может быть пустым"}
  
  validates :phone, length: { is: 11, 
    message: " должен содержать 11 цифр"}
  validates :phone, numericality: { only_integer: true, 
    message: " должен содержать только цифры" }
  validates :phone, :login, :email, uniqueness: { is: true, 
    message: "Уже используется"}

  has_and_belongs_to_many :roles

  def has_role?(name)
    self.roles.where(name: name).length > 0
  end
end

app/models/user_transaction.rb
class UserTransaction < ActiveRecord::Base
	belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	# Prevent CSRF attacks by raising an exception.
	# For APIs, you may want to use :null_session instead.
	include CanCan::ControllerAdditions
	
  	protect_from_forgery with: :exception


	before_action :configure_permitted_parameters, if: :devise_controller?

	protected 

		def configure_permitted_parameters 
			devise_parameter_sanitizer.for(:sign_up) { |u| u.permit(:email, :password, :login, :phone, :role_id) } 
			devise_parameter_sanitizer.for(:account_update) { |u| u.permit(:email, :password, :password_confirmation, :current_password, :login, :phone, :balance) } 
		end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def home
  end

  def game
    @users = User.all
    @games = (Game.order(:rate)).all  
  end

  def about
  end

  def contact
  end

  def about_game
    @game = Game.find_by(id: params[:game])  
  end

  def add_player
    if user_signed_in? 
      @game = Game.find_by(id: params[:id_game])
      if (@game.users.count)<=9
        @find_user = @game.users.where('user_id = ?', current_user.id)
        if @find_user.count == 0
          if (current_user.balance)<(@game.rate)
            flash[:zero_balance] = "Пополните баланс!"
            redirect_to game_path
          else
            @summa = (current_user.balance)-(@game.rate)
            current_user.update_attribute(:balance, @summa)
            if current_user.errors.empty?
              @game.users.push current_user
              flash[:add] = "Вы зарегистрировались. Удачи!"
            else
              flash[:errors] = "Ошибка обратитесь в службу поддержки"
            end
          end

          if (@game.users.count)==10
            @rand = (rand(1..10))-1
            @winner = User.find_by(id: (@game.user_ids[@rand]))
            @update = @game.update_attribute(:winner, @winner.id)
            @win_mon = ((@game.rate)*10) + (@winner.balance)
            @winner.update_attribute(:balance, @win_mon)
            Game.create(rate: @game.rate)
            UserTransaction.create(user_id: @winner.id, sum: @game.rate, satisfy: true, description: "пополнение с игры")
            redirect_to game_path 
          end
        else
          flash[:not_add] = "Вы уже участвуете."
          redirect_to game_path
        end
      else
        flash[:game_full] = "Повторите попытку позже"
        redirect_to game_path
      end
    else
      redirect_to game_path
    end
  end

  def profile
    if user_signed_in? 
      @played_games = current_user.games.where('user_id = ?', current_user.id)
      @transactions = UserTransaction.where('user_id = ?', current_user.id)
      @games = Game.all 
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FastReady</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <%= render 'shader/shim' %>
</head>
<body>
<%= render 'shader/header' %>
	<div class="container">
		<%= yield %>
	</div>
<%= render 'shader/footer' %> 
</body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/about_game.html.erb
<div class="container">
<% if user_signed_in? %>
	<div class="col-md-4" >
		<ul class="list-group">
			<li class="list-group-item">
				<h3 class="panel-title">Игра №<%= @game.id %></h3>
			</li>
			<li class="list-group-item">
					Ставка: <%= @game.rate %> rub
			</li>
			<% if (@game.users.count)<=9 %>
		   		<li class="list-group-item">
					Участники: <%= (@game.users.count) %>/10
					<div class="progress">
					  <div div class="progress-bar progress-bar-success progress-bar-striped active" role="progressbar" aria-valuenow=<%= (@game.users.count)*10 %> aria-valuemin="0" aria-valuemax="100" style="width: <%= (@game.users.count)*10 %>%">
					    <span class="sr-only"><%= (@game.users.count)*10 %>% Complete (success)</span>
					  </div>
					</div>
				</li>
			<% else %>
				<li class="list-group-item">
					Победитель
				</li>
			<% end %>
			<li class="list-group-item">
				Участники: 
				<ol>
					<% (@game.users.where('game_id = ?', @game.id)).each do |gu|%>
						<li><%= gu.login %></li>
					<% end %>
				</ol>
			</li>
			<% if (@game.users.count)<=9 %>
				<% if (@game.users.where('user_id = ?', current_user.id)).count == 0 %>
					<%= link_to "Учавствовать",  {action: 'add_player', id_game: @game.id }, method: :post, :class => "list-group-item list-group-item-success text-center" %>
				<% else %>
					<li class="list-group-item list-group-item-danger text-center">Вы уже учавствуете</li>
				<% end %>
			<% end %>
		</ul>	
	</div>
<% else %>
	<%= render "shader/unincluded" %>
<% end %>
</div>

app/views/pages/contact.html.erb
<div class="container">
	<h2>Обратная связь</h2>
	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">E-mail</span>
		<% if user_signed_in? %>
			<input type="text" class="form-control" value=<%=current_user.email%> aria-describedby="basic-addon1" required></input>
		<% else %>
			<input type="text" class="form-control" placeholder="examlpe@example.com" aria-describedby="basic-addon1" required></input>
		<% end %>
  	</div>
  	<br/>
  	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">Тема сообщения</span>
  		<input type="text" class="form-control" aria-describedby="basic-addon1" required></input>
  	</div>
  	<br/>
  	<div class="input-group">
		<span class="input-group-addon" id="basic-addon1">Текст сообщения</span>
  		<textarea type="text" class="form-control" aria-describedby="basic-addon1" required>
      </textarea>
  	</div>
  	<br/>
  	<input class="btn btn-primary" type="submit" value="Отправить">
</div>

app/views/pages/deposit.html.erb
<div class = "container"> 
    <% if user_signed_in? %>
    	<h1>Страница пополнения баланса</h1>
    <% else %>
    	<%= render "shader/unincluded" %>
    <% end %>
</div>

app/views/pages/game.html.erb
<div class="container">
  <% if user_signed_in? %>
  	<div class="row">
  		<% if flash[:zero_balance]%>
  			<div class="alert alert-danger" role="alert">
  				<%= flash[:zero_balance]%>
  			</div>
  		<% end %>
  		<% if flash[:add]%>
  			<div class="alert alert-success" role="alert">
  				<%= flash[:add]%>
  			</div>
  		<% end %>
  		<% if flash[:not_add]%>
  			<div class="alert alert-warning" role="alert">
  				<%= flash[:not_add]%>
  			</div>
  		<% end %>

  		<div class="jumbotron">
    		<h2 class="text-center">Как проходит мгновенная лотерея</h2>
    		<p>Мгновенная лотерея может состоять из 10 человек. После того как набирается 10 человек, розыгрыш начинается автоматически. Система выбирает случайным образом победителя. Отследить выбор победителя можно в онлайн режиме, после выбора победителя, выйгрыш начисляется на аккаунт победителя.</p>
  		</div>

  		<div class="container">
        <ul class="nav nav-tabs" role="tablist">
          <li role="presentation" class="active"><a href="#active" aria-controls="active" role="tab" data-toggle="tab"><span class="" aria-hidden="true"></span> Активные игры </a></li>
          <li role="presentation"><a href="#end" aria-controls="end" role="tab" data-toggle="tab"><span class="" aria-hidden="true"></span> Завершенные игры</a></li>
        </ul>
        <div class="tab-content">
          <div role="tabpanel" class="tab-pane active" id="active">
            <div class="row" id="game_pad">
              <%= render "shader/game_active" %>
            </div>
          </div>
          <div role="tabpanel" class="tab-pane" id="end">
            <div class="row" id="game_pad">
              <%= render "shader/game_end" %>
            </div>
          </div>
        </div>
  	</div>
  <% else %>
		<%= render "shader/unincluded" %>
  <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div class="container">
	<div class="jumbotron">
	  <h1 class="text-center">Добро пожаловать!</h1>
	  <p>Наш интернет-проект представляет собой совокупность честной, оригинальной, моментальной лотереи. Наш проект предоставляет открытую статистику активных и проведенных играх.</p>
	</div>	
		
    <div class="row">
        <div class="col-md-4" id="home_page">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-check"></i>Мгновенная</h4>
                </div>
                <div class="panel-body">
                    <p>Для победы Вам потребуется только 4 шага:</p>
                    <p>1. <%= link_to "Зарегистрироваться", new_user_registration_path %> или <%= link_to "войти в свой аккаунт", new_user_session_path %></p>
                    <p>2. <%= link_to "Пополнить", deposit_path  %> баланс</p>
                    <p>3. <%= link_to "Выбрать игру", game_path %> с интересующей вас ставкой</p>
                    <p>4. Ожидание розыгрыша</p>
                </div>
            </div>
        </div>
        <div class="col-md-4" id="home_page">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-gift"></i>Вывод раз в сутки</h4>
                </div>
                <div class="panel-body">
                    <p>Вывод денежных средств осуществляется в полуавтоматическом режиме.</p>
                </div>
            </div>
        </div>
        <div class="col-md-4" id="home_page">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h4><i class="fa fa-fw fa-compass"></i>Легкая в использовании</h4>
                </div>
                <div class="panel-body">
                    <p>Наш проект предоставляет простой и легкий сервис минимизирующий количество действий совершаемых пользователем.</p>
                </div>
            </div>
        </div>
    </div>
</div>		

app/views/pages/profile.html.erb
<div class="container">
	<% if user_signed_in? %>
		<h2>Профиль</h2>
		<div class="col-md-4">
			<div class="panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">
						<span class="glyphicon glyphicon-user" aria-hidden="true">
			   	 			<%= current_user.login %></span>
			   	</h3>
				</div>
				<ul class="list-group">
					<li class="list-group-item">
	   	 			<span class="glyphicon glyphicon-envelope" aria-hidden="true">
	   	 				<%= current_user.email %></span>
		   		</li>
		   		<li class="list-group-item">
		   	  		<span class="glyphicon glyphicon-phone" aria-hidden="true">
		   	 			<%= current_user.phone %></span>
		   	 	</li>
		   		<li class="list-group-item">
		   			<span class="glyphicon glyphicon-credit-card" aria-hidden="true">
		   	 			Баланс: <%= current_user.balance %> rub</span>
		   	 	</li>
			  </ul>
		  </div>
		  	<ul class="list-group">
			   	<li class="list-group-item">
	          <%= link_to profile_path do %>
	           	<span class="glyphicon glyphicon-cog"></span> Редактировать
	          <% end %>
	        </li>
			  </ul>
		</div>
		<div class="col-md-8">
			<div>
			  <ul class="nav nav-tabs" role="tablist">
			    <li role="presentation" class="active"><a href="#game" aria-controls="game" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-rub" aria-hidden="true"></span> Розыгрыши</a></li>
			    <li role="presentation"><a href="#trans" aria-controls="trans" role="tab" data-toggle="tab"><span class="glyphicon glyphicon-shopping-cart" aria-hidden="true"></span> Транзакции</a></li>
			  </ul>
			  <div class="tab-content">
			    <div role="tabpanel" class="tab-pane active" id="game">
			    	<%= render 'shader/profile_game' %>
			    </div>
			    <div role="tabpanel" class="tab-pane" id="trans">
			    	<%= render 'shader/profile_transaction' %>
			    </div>
			  </div>
			</div>
		</div>
	<% else %>
		<%= render "shader/unincluded" %>
  <% end %>
</div>

app/views/pages/schedule.html.erb
<div class="jumbotron">
  <h2 class="text-center"><b>Регламент интернет-проекта "ЛОВИ ШАНС"</b></h2>
	<p><t><b>1. Статус и ответственность сторон соглашения</b></p>

	<p>	1.1 Интернет-проекта "ЛОВИ ШАНС"

	<p>1.1.1 Интернет-проект "ЛОВИ ШАНС" является совокупностью размещенных в сети Интернет программ, предназначенных для предоставления пользователям сети удобного автоматизированного интерфейса, позволяющего совершать мгновенные розыгрыши.

	<p>1.1.2 Все расчеты в Интернет-проекте "ЛОВИ ШАНС" осуществляются с помощью платежной системы <a href="https://qiwi.ru/" target="_blank">"QIWI"</a>. Все внутренние расчеты в Интернет-проекте "ЛОВИ ШАНС" осуществляются игровой валютой RUB.

	<p>1.1.3 Деньги на игровой счет зачисляются сразу после перевода. В отдельных случаях при оплате счетов возникают задержки. Эти задержки не превышают 5 минут. Не стоит волноваться, если деньги Вам сразу не зачислились.

	<p>1.1.4 Вывод средств производится в полуавтоматическом режиме в рабочее время, с 09.00 до 19.00 по МСК, кроме субботы и воскресенья. По усмотрению финансовой службы, от Вас могут потребоваться документы, подтверждающие Вашу личность или принадлежность Вам кошелька. Каждый запрос на вывод рассматривается индивидуально.

	<p>1.1.5 Организаторы Интернет-проекта "ЛОВИ ШАНС" не несут ответственности за правомерность и стабильное функционирование платежной системы и сопутствующих ей сервисов.

	<p>1.1.6 Сумма запроса на вывод списывается с Вашего игрового аккаунта сразу. На Ваш кошелек (счет) сумма поступает только после обработки запроса. Если запрос еще не был обработан, то Вы можете отменить запрос на вывод в разделе «История платежей», и сумма вернется на Ваш игровой аккаунт. Внимание! Для формирования запроса на вывод, Вам необходимо совершить сумму ставок равную сумме Вашего депозита.

	<p>1.1.7 Деньги выводятся только на тот кошелек (счет), с которого осуществлялось пополнение игрового аккаунта. 

	<p>1.1.8 Организаторы Интернет-проекта "ЛОВИ ШАНС" имеют право по своему усмотрению отказать пользователю: в предоставлении определенных услуг проекта, с выплатой активной суммы со счета, в случае появления подозрений нечестной игры, накрутке, вмешательства в установленный правилами ход игры, использования программно-аппаратных средств, введения в заблуждение соперников (в чате/ICQ и т.п.), СПАМ-а от имени партнера или игрока проекта "ЛОВИ ШАНС" и иных неправомерных действий пользователя в отношении Интернет-проекта "ЛОВИ ШАНС" или его пользователей. Активная сумма со счета не выплачивается.

	<p>1.1.9 Организаторы Интернет-проекта "ЛОВИ ШАНС" имеют право по своему усмотрению отказать пользователю в предоставлении услуг проекта полностью или частично, если будет выявлен факт злоупотребления правилами, мультиаккаунтство.

	<p>1.1.10 Организаторы Интернет-проекта "ЛОВИ ШАНС" имеют право заблокировать аккаунт партнера, если активность по нему не регистрировалась более 6-ти месяцев, и аккаунт игрока, если активность по нему не регистрировалась более 12 месяцев. Невостребованные в срок суммы на счетах заблокированных аккаунтов не возвращаются. Обратитесь в службу технической поддержки для получения детальной информации.

	<p>1.1.11 Организаторы Интернет-проекта "ЛОВИ ШАНС" не передают личные данные игроков и партнеров, их статистику и иные уникальные данные аккаунтов третьим лицам.

	<p>1.1.12 Организаторы Интернет-проекта "ЛОВИ ШАНС" имеют право в любое время вносить изменения в настоящий Регламент. Новый Регламент вступает в силу с момента его публикации.

	<p>1.1.13 Для предотвращения финансовых махинаций администрация Интернет-проект "ЛОВИ ШАНС" оставляет за собой право требовать документальное свидетельство подтверждающее личность человека и его данные, введенные при регистрации, в том числе контактный телефон. Администрация Интернет-проекта "ЛОВИ ШАНС" вправе заблокировать счет пользователя до предоставления документов подтверждающих личные данные игрока.

	<p>1.1.14 Для блокировки аккаунта необходимо подать запрос, указав причину блокировки. Администрация проекта рассмотрит запрос и примет решение по блокировке/разблокировке аккаунта. Вывод средств с заблокированных аккаунтов может осуществляться на усмотрение администрации проекта, согласно правилам вывода средств.

	<p>1.2 Пользователи и игроки интернет-проекта "ЛОВИ ШАНС"

	<p>1.2.1 Пользователем Интернет-проекта "ЛОВИ ШАНС" может быть любое лицо, пришедшее на сайт <a href="" target="">"Лови шанс"</a> и принимающее на себя обязанности безусловного соблюдения данного Регламента в форме открытой оферты.

	<p>1.2.2 Пользователям Интернет-проекта "ЛОВИ ШАНС", не достигшим 18-летнего возраста, игра запрещена.

	<p>1.2.3 Игроки могут принимать участие в азартных играх, пройдя регистрацию в проекте.

	<p>1.2.4 Игроки не имеют права регистрироваться по своей партнерской ссылке. В случае обнаружения подобного рода накруток, суммы ставок и депозитов не возвращаются, а аккаунт блокируется.

	<p>1.2.5 Игрокам запрещена игра с использованием дополнительных программно-аппаратных средств, функции которых сводятся к прогнозу и автоматизации процесса игры.

	<p>1.2.6 Игрокам запрещено вводить средства со счетов, которые не принадлежат им.

	<p>1.2.7 Пользователь несёт ответственность за хранение своих регистрационных данных. Если пользователь опасается, что эти данные попали в чужие руки, ему следует их сменить.

	<p>1.2.8 Игрок не должен предоставлять доступ к своей странице посторонним лицам, как и не должен разрешать третьим лицам участвовать в игре, которая ведется с использованием баланса игрока.

	<p>1.2.9 Игроки осознают возможность как выигрыша, так и проигрыша.

	<p>1.2.10 Игроки дают согласие на получение важных информационных сообщений по электронной почте.

	<p>1.2.11 Игроки дают согласие на открытую публикацию обезличенной статистической информации.

	<p>1.2.12 Попытки стороннего вмешательства в процесс игры с целью подтасовки результата или нарушения работы сайта наказываются блокировкой. Находящиеся на счету средства не возвращаются.

	<p>1.2.13 Все спорные вопросы будут разрешаться путем переговоров. Любые убытки, которые посетитель может понести в случае умышленного или неосторожного нарушения любого требования данного Регламента, организаторами Интернет-проекта "ЛОВИ ШАНС" не возмещаются.

	<p>1.2.14 Игроки подтверждают полное согласие с правилами игр в том виде, в котором они действуют на момент совершения каждой отдельной ставки.

	<p>1.3 Партнеры интернет-проекта "ЛОВИ ШАНС"

	<p>1.3.1 Партнером Интернет-проекта "ЛОВИ ШАНС" может быть любое лицо, прошедшее регистрацию на сайте <a href="" target="">"Лови шанс"</a> и принимающее на себя обязанности безусловного соблюдения данного Регламента в форме открытой оферты.

	<p>1.3.2 Партнеры Интернет-проекта "ЛОВИ ШАНС" имеют право использовать готовые баннеры или баннеры собственной разработки, не противоречащие этическим и законодательным нормам, установленным для интернет-рекламы.

	<p>1.3.3 Партнеры Интернет-проекта "ЛОВИ ШАНС" имеют право рекламировать партнерскую ссылку всеми известными способами, исключая СПАМ рассылку и иные виды рекламы, противоречащие этическим и законодательным нормам, установленным для интернет-рекламы.

	<p>1.3.4 Партнеры не имеют права принимать участие в играх на сайте <a href="" target="">"Лови шанс"</a>, используя свою партнерскую ссылку! Несоблюдение данного условия влечет за собой блокировку аккаунта Партнера и отказ от дальнейшего сотрудничества. Находящиеся на счету Партнера средства не возвращаются.

	<p>1.3.5 Партнеры дают согласие на получение важных информационных сообщений по электронной почте.

	<p>1.3.6 Партнерское вознаграждение не начисляется партнеру, если игрок, закрепленный за партнером, нарушил текущие правила проекта.

	<p>1.3.7 В партнерской программе учитываются игроки совершившие депозит.

	<p>2. Отсутствие гарантий со стороны организаторов интернет-проекта "ЛОВИ ШАНС"

	<p>2.1 Организаторы Интернет-проекта "ЛОВИ ШАНС" не гарантируют постоянный или безусловный доступ к предоставляемым услугам. Функционирование проекта может нарушаться действиями непреодолимых сил и иных факторов, предотвращение или преодоление которых выходит за пределы возможностей организаторов Интернет-проекта "ЛОВИ ШАНС".

	<p>3. Заключительные положения

	<p>3.1 Все спорные вопросы будут разрешаться путем переговоров.

	<p>3.2 Любые убытки, которые Пользователь может понести в случае умышленного или неосторожного нарушения любого требования данного Регламента, организаторами Интернет-проекта "ЛОВИ ШАНС" не возмещаются.

	<p>Редакция от 2016-02-22
</div>

app/views/pages/withdraw.html.erb
<div class="container">
	<% if user_signed_in? %>
		<h2>Страница для вывода</h2>
		<p> Для вывода средств со счета вам нужно иметь минимум 100 рублей </p>
	<% else %>
		<%= render "shader/unincluded" %>
	<% end %>
</div>

app/views/shader/_footer.html.erb
<footer class="footer">
	<small>
	  by Lafa
	  </br>
	  2016
	</small>
	<nav>
		<ul>
	  	<li><%= link_to "Правила", schedule_path %></li>
	  </ul>
	</nav>
</footer>

app/views/shader/_game_end.html.erb
<div class="container">
	<% @games.each do |g| %>
	<% if (g.users.count)>=10 %>
		<div class="col-md-4" >
			<div class="panel panel-default" id="new_game">
				<div class="panel-heading">
					<h3 class="panel-title">Игра №<%= g.id %></h3>
				</div>
				<ul class="list-group">
					<li class="list-group-item">
		   	 			<span class="glyphicon glyphicon-king" aria-hidden="true">
		   	 				Ставка: <%= g.rate %> rub</span>
			   		</li>
					<li class="list-group-item">
		   	 			<span class="glyphicon glyphicon-king" aria-hidden="true">
		   	 				Победитель: <%= (@users.find_by('id = ?', (g.winner))).login %></span>
			   		</li>
			   		<li class="list-group-item">
			   			<span class="" aria-hidden="true">
							Участники:
									<% (g.users.where('game_id = ?', g.id)).each do |gu|%>
											<%=gu.id%><%= gu.login %>
							<% end %>
						</span>
					</li>
				</ul>		
			</div>
		</div>
	<% end %>
<% end %>
</div>

app/views/shader/_header.html.erb
<div class="navbar navbar-default navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="/">Лови шанс</a>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            <li>
              <%= link_to 'Начать', game_path %>
            </li>
            <li>
              <%= link_to 'О нас', about_path %>
            </li>
            <li>
              <%= link_to 'Контакты', contact_path %>
            </li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown" href="" role="button" aria-haspopup="true" aria-expanded="false"><span class="glyphicon glyphicon-credit-card"></span> Баланс: <%= current_user.balance %> rub <span class="caret"></span>
                </a>
                <ul class="dropdown-menu">
                  <li><%= link_to "Пополнить", deposit_path %></li>
                  <li role="separator" class="divider"></li>
                  <li><%= link_to "Снять", withdraw_path %></li>
                </ul>
              </li>
              <li>
                  <%= link_to profile_path do %>
                  <span class="glyphicon glyphicon-user"></span> Профиль
                  <% end %>
              </li>
              <li>
                <%= link_to destroy_user_session_path, method: :delete do %>
                  <span class="glyphicon glyphicon-log-out"></span> Выход
                <% end %>
              </li>
            <% else %>
              <li>
              <%= link_to new_user_registration_path do %>
                  <span class="glyphicon glyphicon-expand"></span> Регистрация
              <% end %>
              </li>
              <li>
              <%= link_to new_user_session_path do %>
                  <span class="glyphicon glyphicon-log-in"></span> Вход
              <% end %>
              </li>
          <% end %>
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </div>

app/views/shader/_shim.html.erb
<!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->